CREATE DATABASE IF NOT EXISTS BD_MERCADO;
USE BD_MERCADO;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CPF_CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    LOGO BLOB NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL 
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	CODIGO_DE_BARRAS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    LOGO BLOB NOT NULL,
    VALOR INT NOT NULL,
    FK_ID_CATEGORIA INT,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) 
);

CREATE TABLE IF NOT EXISTS FORNECEDOR_PRODUTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_CPF_CNPJ_FORNECEDOR VARCHAR(14),
    FOREIGN KEY (FK_CPF_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CPF_CNPJ),
     FK_COD_BARRAS_PRODUTO INT,
    FOREIGN KEY (FK_COD_BARRAS_PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS)
);