CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL 
);


CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    RITMO VARCHAR(50) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ESTILO VARCHAR(50) NOT NULL 
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TEMPO VARCHAR(50) NOT NULL,
    DATA_LANCAMENTO DATE  NOT NULL,
    FK_CPF_ARTISTA VARCHAR(11),
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF) 
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    LETRA VARCHAR(255) NOT NULL,
    CAPA BLOB NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    FK_ID_ALBUM INT,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
	FK_ID_GENERO INT,
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID) 
);